// <auto-generated />
namespace BooksBlog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addidtopost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addidtopost));
        
        string IMigrationMetadata.Id
        {
            get { return "201612061344407_add id to post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
